### ISSUE TITLE
Panic on Mac

### ISSUE THREAD

**Issue by mgr-inz-rafal** [synek317/shellfn#8]
I'm using: `Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64`

Running a project that uses `shellfn` on Mac results in the following error message:

```
[      0/5      ] ----------------------------------------------------------------------------------------------------  Elapsed: 00:00:00 ETA: 0s
thread 'main' panicked at 'Shell execution failed', /Users/rch/.cargo/registry/src/github.com-1ecc6299db9ec823/shellfn-core-0.1.1/src/execute/item.rs:86:9
```

The same project runs correctly on Linux Mint.

**Comment by synek317** [comment]
It turned out the issue is related to a different poject.
